# This file creates a R image
# for cooperative learning

FROM rocker/tidyverse

# Install required packages
RUN Rscript -e "install.packages('glmnet')"
RUN Rscript -e "install.packages('randomForest')"