name: Publish multi_omics dockerfiles on DockerHub
on: 
  push: 
    paths: 
      - 'docker/cooperative_learning/Dockerfile'
      #- 'docker/<method_name>/Dockerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
      id: bump
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.bump.outputs.new_tag }}
        release_name: ${{ steps.bump.outputs.new_tag }}
        body: |
          Changes in this Release
          - Rebuilt cooperative learning Docker image and published to DockerHub with new tag
        draft: false
        prerelease: false
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: tonyliang19/cooperative_learning
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: docker/cooperative_learning
        tags: "latest,${{ steps.bump.outputs.new_tag }}"
    #- name: Publish to Registry
    #  uses: elgohr/Publish-Docker-Github-Action@v4
    #  with:
    #    name: tonyliang19/r-stat-301-grading
    #    username: ${{ secrets.DOCKER_USERNAME }}
    #    password: ${{ secrets.DOCKER_PASSWORD }}
    #    workdir: dockerfiles/r-stat-301-grading
    #    tags: "latest,${{ steps.bump.outputs.new_tag }}"
